name: Commit to main
on:
  push: # Trigger the workflow on push events but only for the main branch
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Versions
        run: yarn -v && node -v && npm -v
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
